//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/model/BusinessAddressHolder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BusinessAddressHolder")
#ifdef RESTRICT_BusinessAddressHolder
#define INCLUDE_ALL_BusinessAddressHolder 0
#else
#define INCLUDE_ALL_BusinessAddressHolder 1
#endif
#undef RESTRICT_BusinessAddressHolder

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpBusinessAddressHolder_) && (INCLUDE_ALL_BusinessAddressHolder || defined(INCLUDE_EmpBusinessAddressHolder))
#define EmpBusinessAddressHolder_

#define RESTRICT_AddressHolder 1
#define INCLUDE_EmpAddressHolder 1
#include "AddressHolder.h"

@class EmpBusinessAddress;

@interface EmpBusinessAddressHolder : EmpAddressHolder

#pragma mark Public

- (instancetype __nonnull)init;

- (EmpBusinessAddress *)getMax;

- (EmpBusinessAddress *)getMin;

@end

J2OBJC_EMPTY_STATIC_INIT(EmpBusinessAddressHolder)

FOUNDATION_EXPORT void EmpBusinessAddressHolder_init(EmpBusinessAddressHolder *self);

FOUNDATION_EXPORT EmpBusinessAddressHolder *new_EmpBusinessAddressHolder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpBusinessAddressHolder *create_EmpBusinessAddressHolder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EmpBusinessAddressHolder)

@compatibility_alias ComEmployeeModelBusinessAddressHolder EmpBusinessAddressHolder;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_BusinessAddressHolder")
