//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/model/Employee.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Employee")
#ifdef RESTRICT_Employee
#define INCLUDE_ALL_Employee 0
#else
#define INCLUDE_ALL_Employee 1
#endif
#undef RESTRICT_Employee

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpEmployee_) && (INCLUDE_ALL_Employee || defined(INCLUDE_EmpEmployee))
#define EmpEmployee_

@class EmpAddressHolder;
@class IOSLongArray;
@class JavaUtilDate;
@protocol JavaUtilList;
@protocol JavaUtilMap;

@interface EmpEmployee : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (EmpAddressHolder *)getAddressHolder;

- (JavaUtilDate *)getBirthDate;

- (id<JavaUtilList>)getCities;

- (jint)getId;

- (NSString *)getName;

- (IOSLongArray *)getPhoneNumbers;

- (id<JavaUtilMap>)getProperties;

- (NSString *)getRole;

- (jboolean)isPermanent;

- (void)setAddressHolderWithEmpAddressHolder:(EmpAddressHolder *)addressHolder;

- (void)setBirthDateWithJavaUtilDate:(JavaUtilDate *)birthDate;

- (void)setCitiesWithJavaUtilList:(id<JavaUtilList>)cities;

- (void)setIdWithInt:(jint)id_;

- (void)setNameWithNSString:(NSString *)name;

- (void)setPermanentWithBoolean:(jboolean)permanent;

- (void)setPhoneNumbersWithLongArray:(IOSLongArray *)phoneNumbers;

- (void)setPropertiesWithJavaUtilMap:(id<JavaUtilMap>)properties;

- (void)setRoleWithNSString:(NSString *)role;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(EmpEmployee)

FOUNDATION_EXPORT void EmpEmployee_init(EmpEmployee *self);

FOUNDATION_EXPORT EmpEmployee *new_EmpEmployee_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpEmployee *create_EmpEmployee_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EmpEmployee)

@compatibility_alias ComEmployeeModelEmployee EmpEmployee;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Employee")
