//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/gson/EmployeeGsonExample.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EmployeeGsonExample")
#ifdef RESTRICT_EmployeeGsonExample
#define INCLUDE_ALL_EmployeeGsonExample 0
#else
#define INCLUDE_ALL_EmployeeGsonExample 1
#endif
#undef RESTRICT_EmployeeGsonExample

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpEmployeeGsonExample_) && (INCLUDE_ALL_EmployeeGsonExample || defined(INCLUDE_EmpEmployeeGsonExample))
#define EmpEmployeeGsonExample_

@class EmpEmployee;
@class EmpEmployeeService;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface EmpEmployeeGsonExample : NSObject

+ (EmpEmployeeService *)employeeService;

+ (void)setEmployeeService:(EmpEmployeeService *)value;

#pragma mark Public

- (instancetype __nonnull)init;

+ (void)convertEmployee;

+ (id<JavaUtilList>)convertEmployeesWithInt:(jint)numberOfEmployees;

+ (EmpEmployee *)createEmployeeWithInt:(jint)id_;

+ (id<JavaUtilList>)createEmployeesWithInt:(jint)numberOfEmployees;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_STATIC_INIT(EmpEmployeeGsonExample)

inline EmpEmployeeService *EmpEmployeeGsonExample_get_employeeService(void);
inline EmpEmployeeService *EmpEmployeeGsonExample_set_employeeService(EmpEmployeeService *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT EmpEmployeeService *EmpEmployeeGsonExample_employeeService;
J2OBJC_STATIC_FIELD_OBJ(EmpEmployeeGsonExample, employeeService, EmpEmployeeService *)

FOUNDATION_EXPORT void EmpEmployeeGsonExample_init(EmpEmployeeGsonExample *self);

FOUNDATION_EXPORT EmpEmployeeGsonExample *new_EmpEmployeeGsonExample_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpEmployeeGsonExample *create_EmpEmployeeGsonExample_init(void);

FOUNDATION_EXPORT void EmpEmployeeGsonExample_mainWithNSStringArray_(IOSObjectArray *args);

FOUNDATION_EXPORT void EmpEmployeeGsonExample_convertEmployee(void);

FOUNDATION_EXPORT EmpEmployee *EmpEmployeeGsonExample_createEmployeeWithInt_(jint id_);

FOUNDATION_EXPORT id<JavaUtilList> EmpEmployeeGsonExample_createEmployeesWithInt_(jint numberOfEmployees);

FOUNDATION_EXPORT id<JavaUtilList> EmpEmployeeGsonExample_convertEmployeesWithInt_(jint numberOfEmployees);

J2OBJC_TYPE_LITERAL_HEADER(EmpEmployeeGsonExample)

@compatibility_alias ComEmployeeGsonEmployeeGsonExample EmpEmployeeGsonExample;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EmployeeGsonExample")
