//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/JsonObject.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonObject")
#ifdef RESTRICT_JsonObject
#define INCLUDE_ALL_JsonObject 0
#else
#define INCLUDE_ALL_JsonObject 1
#endif
#undef RESTRICT_JsonObject

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonJsonObject_) && (INCLUDE_ALL_JsonObject || defined(INCLUDE_GsonJsonObject))
#define GsonJsonObject_

#define RESTRICT_JsonElement 1
#define INCLUDE_GsonJsonElement 1
#include "JsonElement.h"

@class GsonJsonArray;
@class GsonJsonPrimitive;
@class JavaLangBoolean;
@class JavaLangCharacter;
@protocol JavaUtilSet;

/*!
 @brief A class representing an object type in Json.An object consists of name-value pairs where names
  are strings, and values are any other type of <code>JsonElement</code>.
 This allows for a creating a
  tree of JsonElements. The member elements of this object are maintained in order they were added.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@interface GsonJsonObject : GsonJsonElement

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @brief Adds a member, which is a name-value pair, to self.The name must be a String, but the value
  can be an arbitrary JsonElement, thereby allowing you to build a full tree of JsonElements
  rooted at this node.
 @param property name of the member.
 @param value the member object.
 */
- (void)addWithNSString:(NSString *)property
    withGsonJsonElement:(GsonJsonElement *)value;

/*!
 @brief Convenience method to add a boolean member.The specified value is converted to a
  JsonPrimitive of Boolean.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
            withJavaLangBoolean:(JavaLangBoolean *)value;

/*!
 @brief Convenience method to add a char member.The specified value is converted to a
  JsonPrimitive of Character.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
          withJavaLangCharacter:(JavaLangCharacter *)value;

/*!
 @brief Convenience method to add a primitive member.The specified value is converted to a
  JsonPrimitive of Number.
 @param property name of the member.
 @param value the number value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
                   withNSNumber:(NSNumber *)value;

/*!
 @brief Convenience method to add a primitive member.The specified value is converted to a
  JsonPrimitive of String.
 @param property name of the member.
 @param value the string value associated with the member.
 */
- (void)addPropertyWithNSString:(NSString *)property
                   withNSString:(NSString *)value;

/*!
 @brief Returns a set of members of this object.The set is ordered, and the order is in which the
  elements were added.
 @return a set of members of this object.
 */
- (id<JavaUtilSet>)entrySet;

- (jboolean)isEqual:(id)o;

/*!
 @brief Returns the member with the specified name.
 @param memberName name of the member that is being requested.
 @return the member matching the name. Null if no such member exists.
 */
- (GsonJsonElement *)getWithNSString:(NSString *)memberName;

/*!
 @brief Convenience method to get the specified member as a JsonArray.
 @param memberName name of the member being requested.
 @return the JsonArray corresponding to the specified member.
 */
- (GsonJsonArray *)getAsJsonArrayWithNSString:(NSString *)memberName;

/*!
 @brief Convenience method to get the specified member as a JsonObject.
 @param memberName name of the member being requested.
 @return the JsonObject corresponding to the specified member.
 */
- (GsonJsonObject *)getAsJsonObjectWithNSString:(NSString *)memberName;

/*!
 @brief Convenience method to get the specified member as a JsonPrimitive element.
 @param memberName name of the member being requested.
 @return the JsonPrimitive corresponding to the specified member.
 */
- (GsonJsonPrimitive *)getAsJsonPrimitiveWithNSString:(NSString *)memberName;

/*!
 @brief Convenience method to check if a member with the specified name is present in this object.
 @param memberName name of the member that is being checked for presence.
 @return true if there is a member with the specified name, false otherwise.
 */
- (jboolean)hasWithNSString:(NSString *)memberName;

- (NSUInteger)hash;

/*!
 @brief Removes the <code>property</code> from this <code>JsonObject</code>.
 @param property name of the member that should be removed.
 @return the <code>JsonElement</code> object that is being removed.
 @since 1.3
 */
- (GsonJsonElement *)removeWithNSString:(NSString *)property;

/*!
 @brief Returns the number of key/value pairs in the object.
 @return the number of key/value pairs in the object.
 */
- (jint)size;

#pragma mark Package-Private

- (GsonJsonObject *)deepCopy;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonJsonObject)

FOUNDATION_EXPORT void GsonJsonObject_init(GsonJsonObject *self);

FOUNDATION_EXPORT GsonJsonObject *new_GsonJsonObject_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonObject *create_GsonJsonObject_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonObject)

@compatibility_alias ComGoogleGsonJsonObject GsonJsonObject;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JsonObject")
