//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/internal/ObjectConstructor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectConstructor")
#ifdef RESTRICT_ObjectConstructor
#define INCLUDE_ALL_ObjectConstructor 0
#else
#define INCLUDE_ALL_ObjectConstructor 1
#endif
#undef RESTRICT_ObjectConstructor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonObjectConstructor_) && (INCLUDE_ALL_ObjectConstructor || defined(INCLUDE_GsonObjectConstructor))
#define GsonObjectConstructor_

/*!
 @brief Defines a generic object construction factory.The purpose of this class
  is to construct a default instance of a class that can be used for object
  navigation while deserialization from its JSON representation.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@protocol GsonObjectConstructor < JavaObject >

/*!
 @brief Returns a new instance.
 */
- (id)construct;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonObjectConstructor)

J2OBJC_TYPE_LITERAL_HEADER(GsonObjectConstructor)

#define ComGoogleGsonInternalObjectConstructor GsonObjectConstructor

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ObjectConstructor")
