//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/internal/bind/ObjectTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectTypeAdapter")
#ifdef RESTRICT_ObjectTypeAdapter
#define INCLUDE_ALL_ObjectTypeAdapter 0
#else
#define INCLUDE_ALL_ObjectTypeAdapter 1
#endif
#undef RESTRICT_ObjectTypeAdapter

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonObjectTypeAdapter_) && (INCLUDE_ALL_ObjectTypeAdapter || defined(INCLUDE_GsonObjectTypeAdapter))
#define GsonObjectTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_GsonTypeAdapter 1
#include "TypeAdapter.h"

@class GsonGson;
@class GsonJsonReader;
@class GsonJsonWriter;
@protocol GsonTypeAdapterFactory;

/*!
 @brief Adapts types whose static type is only 'Object'.Uses getClass() on
  serialization and a primitive/Map/List on deserialization.
 */
@interface GsonObjectTypeAdapter : GsonTypeAdapter

+ (id<GsonTypeAdapterFactory>)FACTORY;

#pragma mark Public

- (id)readWithGsonJsonReader:(GsonJsonReader *)inArg;

- (void)writeWithGsonJsonWriter:(GsonJsonWriter *)outArg
                         withId:(id)value;

#pragma mark Package-Private

- (instancetype __nonnull)initWithGsonGson:(GsonGson *)gson;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GsonObjectTypeAdapter)

inline id<GsonTypeAdapterFactory> GsonObjectTypeAdapter_get_FACTORY(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<GsonTypeAdapterFactory> GsonObjectTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GsonObjectTypeAdapter, FACTORY, id<GsonTypeAdapterFactory>)

FOUNDATION_EXPORT void GsonObjectTypeAdapter_initWithGsonGson_(GsonObjectTypeAdapter *self, GsonGson *gson);

FOUNDATION_EXPORT GsonObjectTypeAdapter *new_GsonObjectTypeAdapter_initWithGsonGson_(GsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonObjectTypeAdapter *create_GsonObjectTypeAdapter_initWithGsonGson_(GsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(GsonObjectTypeAdapter)

@compatibility_alias ComGoogleGsonInternalBindObjectTypeAdapter GsonObjectTypeAdapter;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ObjectTypeAdapter")
