//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/model/AddressHolder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AddressHolder")
#ifdef RESTRICT_AddressHolder
#define INCLUDE_ALL_AddressHolder 0
#else
#define INCLUDE_ALL_AddressHolder 1
#endif
#undef RESTRICT_AddressHolder

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpAddressHolder_) && (INCLUDE_ALL_AddressHolder || defined(INCLUDE_EmpAddressHolder))
#define EmpAddressHolder_

@class EmpAddress;

@interface EmpAddressHolder : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (EmpAddress *)getMax;

- (EmpAddress *)getMin;

- (void)setMaxWithEmpAddress:(EmpAddress *)max;

- (void)setMinWithEmpAddress:(EmpAddress *)min;

@end

J2OBJC_EMPTY_STATIC_INIT(EmpAddressHolder)

FOUNDATION_EXPORT void EmpAddressHolder_init(EmpAddressHolder *self);

FOUNDATION_EXPORT EmpAddressHolder *new_EmpAddressHolder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpAddressHolder *create_EmpAddressHolder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EmpAddressHolder)

@compatibility_alias ComEmployeeModelAddressHolder EmpAddressHolder;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AddressHolder")
