//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/model/Address.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Address")
#ifdef RESTRICT_Address
#define INCLUDE_ALL_Address 0
#else
#define INCLUDE_ALL_Address 1
#endif
#undef RESTRICT_Address

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpAddress_) && (INCLUDE_ALL_Address || defined(INCLUDE_EmpAddress))
#define EmpAddress_

@interface EmpAddress : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (NSString *)getCity;

- (id)getFreeText;

- (NSString *)getStreet;

- (jint)getZipcode;

- (void)setCityWithNSString:(NSString *)city;

- (void)setFreeTextWithId:(id)freeText;

- (void)setStreetWithNSString:(NSString *)street;

- (void)setZipcodeWithInt:(jint)zipcode;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(EmpAddress)

FOUNDATION_EXPORT void EmpAddress_init(EmpAddress *self);

FOUNDATION_EXPORT EmpAddress *new_EmpAddress_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpAddress *create_EmpAddress_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EmpAddress)

@compatibility_alias ComEmployeeModelAddress EmpAddress;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Address")
