//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/gson/EmployeeService.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EmployeeService")
#ifdef RESTRICT_EmployeeService
#define INCLUDE_ALL_EmployeeService 0
#else
#define INCLUDE_ALL_EmployeeService 1
#endif
#undef RESTRICT_EmployeeService

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (EmpEmployeeService_) && (INCLUDE_ALL_EmployeeService || defined(INCLUDE_EmpEmployeeService))
#define EmpEmployeeService_

@class EmpEmployee;
@protocol JavaUtilList;

@interface EmpEmployeeService : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (EmpEmployee *)employeeFromJsonWithNSString:(NSString *)employeeJson;

- (id<JavaUtilList>)employeesFromJsonWithNSString:(NSString *)employeesJson;

- (NSString *)employeesToJsonWithJavaUtilList:(id<JavaUtilList>)employees;

- (NSString *)employeeToJsonWithEmpEmployee:(EmpEmployee *)employee;

@end

J2OBJC_EMPTY_STATIC_INIT(EmpEmployeeService)

FOUNDATION_EXPORT void EmpEmployeeService_init(EmpEmployeeService *self);

FOUNDATION_EXPORT EmpEmployeeService *new_EmpEmployeeService_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EmpEmployeeService *create_EmpEmployeeService_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EmpEmployeeService)

@compatibility_alias ComEmployeeGsonEmployeeService EmpEmployeeService;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EmployeeService")
