//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/internal/bind/JsonTreeWriter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonTreeWriter")
#ifdef RESTRICT_JsonTreeWriter
#define INCLUDE_ALL_JsonTreeWriter 0
#else
#define INCLUDE_ALL_JsonTreeWriter 1
#endif
#undef RESTRICT_JsonTreeWriter

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonJsonTreeWriter_) && (INCLUDE_ALL_JsonTreeWriter || defined(INCLUDE_GsonJsonTreeWriter))
#define GsonJsonTreeWriter_

#define RESTRICT_JsonWriter 1
#define INCLUDE_GsonJsonWriter 1
#include "JsonWriter.h"

@class GsonJsonElement;
@class JavaIoWriter;
@class JavaLangBoolean;

/*!
 @brief This writer creates a JsonElement.
 */
@interface GsonJsonTreeWriter : GsonJsonWriter

#pragma mark Public

- (instancetype __nonnull)init;

- (GsonJsonWriter *)beginArray;

- (GsonJsonWriter *)beginObject;

- (void)close;

- (GsonJsonWriter *)endArray;

- (GsonJsonWriter *)endObject;

- (void)flush;

/*!
 @brief Returns the top level object produced by this writer.
 */
- (GsonJsonElement *)get;

- (GsonJsonWriter *)nameWithNSString:(NSString *)name;

- (GsonJsonWriter *)nullValue;

- (GsonJsonWriter *)valueWithBoolean:(jboolean)value;

- (GsonJsonWriter *)valueWithJavaLangBoolean:(JavaLangBoolean *)value;

- (GsonJsonWriter *)valueWithDouble:(jdouble)value;

- (GsonJsonWriter *)valueWithLong:(jlong)value;

- (GsonJsonWriter *)valueWithNSNumber:(NSNumber *)value;

- (GsonJsonWriter *)valueWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaIoWriter:(JavaIoWriter *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GsonJsonTreeWriter)

FOUNDATION_EXPORT void GsonJsonTreeWriter_init(GsonJsonTreeWriter *self);

FOUNDATION_EXPORT GsonJsonTreeWriter *new_GsonJsonTreeWriter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonTreeWriter *create_GsonJsonTreeWriter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonTreeWriter)

@compatibility_alias ComGoogleGsonInternalBindJsonTreeWriter GsonJsonTreeWriter;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JsonTreeWriter")
