//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/JsonNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonNull")
#ifdef RESTRICT_JsonNull
#define INCLUDE_ALL_JsonNull 0
#else
#define INCLUDE_ALL_JsonNull 1
#endif
#undef RESTRICT_JsonNull

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonJsonNull_) && (INCLUDE_ALL_JsonNull || defined(INCLUDE_GsonJsonNull))
#define GsonJsonNull_

#define RESTRICT_JsonElement 1
#define INCLUDE_GsonJsonElement 1
#include "JsonElement.h"

/*!
 @brief A class representing a Json <code>null</code> value.
 @author Inderjeet Singh
 @author Joel Leitch
 @since 1.2
 */
@interface GsonJsonNull : GsonJsonElement

+ (GsonJsonNull *)INSTANCE;

#pragma mark Public

/*!
 @brief Creates a new JsonNull object.
 Deprecated since Gson version 1.8. Use <code>INSTANCE</code> instead
 */
- (instancetype __nonnull)init;

/*!
 @brief All instances of JsonNull are the same
 */
- (jboolean)isEqual:(id)other;

/*!
 @brief All instances of JsonNull have the same hash code since they are indistinguishable
 */
- (NSUInteger)hash;

#pragma mark Package-Private

- (GsonJsonNull *)deepCopy;

@end

J2OBJC_STATIC_INIT(GsonJsonNull)

/*!
 @brief singleton for JsonNull
 @since 1.8
 */
inline GsonJsonNull *GsonJsonNull_get_INSTANCE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT GsonJsonNull *GsonJsonNull_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GsonJsonNull, INSTANCE, GsonJsonNull *)

FOUNDATION_EXPORT void GsonJsonNull_init(GsonJsonNull *self);

FOUNDATION_EXPORT GsonJsonNull *new_GsonJsonNull_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonJsonNull *create_GsonJsonNull_init(void);

J2OBJC_TYPE_LITERAL_HEADER(GsonJsonNull)

@compatibility_alias ComGoogleGsonJsonNull GsonJsonNull;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JsonNull")
