//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/internal/LazilyParsedNumber.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LazilyParsedNumber")
#ifdef RESTRICT_LazilyParsedNumber
#define INCLUDE_ALL_LazilyParsedNumber 0
#else
#define INCLUDE_ALL_LazilyParsedNumber 1
#endif
#undef RESTRICT_LazilyParsedNumber

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GsonLazilyParsedNumber_) && (INCLUDE_ALL_LazilyParsedNumber || defined(INCLUDE_GsonLazilyParsedNumber))
#define GsonLazilyParsedNumber_

/*!
 @brief This class holds a number value that is lazily converted to a specific number type
 @author Inderjeet Singh
 */
@interface GsonLazilyParsedNumber : NSNumber

#pragma mark Public

/*!
 @param value must not be null
 */
- (instancetype __nonnull)initWithNSString:(NSString *)value;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)obj;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jlong)longLongValue;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GsonLazilyParsedNumber)

FOUNDATION_EXPORT void GsonLazilyParsedNumber_initWithNSString_(GsonLazilyParsedNumber *self, NSString *value);

FOUNDATION_EXPORT GsonLazilyParsedNumber *new_GsonLazilyParsedNumber_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GsonLazilyParsedNumber *create_GsonLazilyParsedNumber_initWithNSString_(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(GsonLazilyParsedNumber)

@compatibility_alias ComGoogleGsonInternalLazilyParsedNumber GsonLazilyParsedNumber;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_LazilyParsedNumber")
