//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/google/gson/internal/package-info.java
//

/*!
 @brief Do NOT use any class in this package as they are meant for internal use in Gson.
 These classes will very likely change incompatibly in future versions. You have been warned.
 @author Inderjeet Singh, Joel Leitch, Jesse Wilson
 */
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Package_info")
#ifdef RESTRICT_Package_info
#define INCLUDE_ALL_Package_info 0
#else
#define INCLUDE_ALL_Package_info 1
#endif
#undef RESTRICT_Package_info

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Package_info")
