//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./src/main/java/com/employee/model/PersonalAddressHolder.java
//

#include "AddressHolder.h"
#include "J2ObjC_source.h"
#include "PersonalAddressHolder.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

#line 1 "/Users/ahmedmohammed/intelliJWorkspace/employee-gson/src/main/java/com/employee/model/PersonalAddressHolder.java"


#line 3
@implementation EmpPersonalAddressHolder

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 3
- (instancetype)init {
  EmpPersonalAddressHolder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "Lcom/employee/model/AddressHolder<Lcom/employee/model/PersonalAddress;>;" };
  static const J2ObjcClassInfo _EmpPersonalAddressHolder = { "PersonalAddressHolder", "com.employee.model", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, 0, -1 };
  return &_EmpPersonalAddressHolder;
}

@end


#line 3
void EmpPersonalAddressHolder_init(EmpPersonalAddressHolder *self) {
  EmpAddressHolder_init(self);
}


#line 3
EmpPersonalAddressHolder *new_EmpPersonalAddressHolder_init() {
  J2OBJC_NEW_IMPL(EmpPersonalAddressHolder, init)
}


#line 3
EmpPersonalAddressHolder *create_EmpPersonalAddressHolder_init() {
  J2OBJC_CREATE_IMPL(EmpPersonalAddressHolder, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EmpPersonalAddressHolder)

J2OBJC_NAME_MAPPING(EmpPersonalAddressHolder, "com.employee.model", "Emp")
